version: '3'

services:
  otel-collector:
    build: aws-otel-collector
    ports:
      - "4317:4317"
      - "4318:4318"
    environment:
      AWS_ACCESS_KEY_ID: a
      AWS_SECRET_ACCESS_KEY: b
      AWS_SESSION_TOKEN: c
      AWS_REGION: eu-central-1
  python-webapp:
    build: python-webapp
    ports:
      - "7777:7777"
    depends_on:
      - otel-collector
