extensions:
  health_check:
  pprof:
    endpoint: 0.0.0.0:1777

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  datadog:
    api:
      key: "aa14c6910f22009f4c587505b0eb3387"
      site: datadoghq.eu
  logging:
    loglevel: debug
  awsxray:
    region: 'eu-central-1'
  awsemf:
    region: 'eu-central-1'
  otlp:
    endpoint: https://otlp.eu01.nr-data.net:4317
    headers:
      "api-key": "token"
  otlp/2:
    endpoint: api.honeycomb.io:443
    headers:
      x-honeycomb-team: "token"
      x-honeycomb-dataset: "testapp"
  otlp/3:
    endpoint: ingest.lightstep.com:443
    headers:
      lightstep-access-token: "token"
  otlp/4:
    endpoint: tempo-eu-west-0.grafana.net:443
    headers:
      authorization: "Basic token"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [datadog, otlp, otlp/2, otlp/3, otlp/4]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [datadog, otlp, otlp/2, otlp/3, otlp/4]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]

  extensions: [pprof]
  telemetry:
    logs:
      level: debug
