extensions:
  health_check:
  pprof:
    endpoint: 0.0.0.0:1777

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  datadog:
    api:
      key: ""
      site: datadoghq.eu
  logging:
    loglevel: debug
  awsxray:
    region: 'eu-central-1'
  awsemf:
    region: 'eu-central-1'
  otlp:
    endpoint: https://otlp.nr-data.net:4317
    headers:
      "api-key": ""

service:
  pipelines:
    traces:
      receivers: [otlp]
#      processors: [batch]
      exporters: [datadog, otlp]
    metrics:
      receivers: [otlp]
#      processors: [batch]
      exporters: [datadog, otlp]
#    logs:
#      receivers: [otlp]
#      processors: [batch]
#      exporters: [otlp]

  extensions: [pprof]
  telemetry:
    logs:
      level: debug
