extensions:
  health_check:
  pprof:
    endpoint: 0.0.0.0:1777

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  batch:

exporters:
  datadog:
    api:
      key: ""
      site: datadoghq.eu
  logging:
    loglevel: debug
  awsxray:
    region: 'eu-central-1'
  awsemf:
    region: 'eu-central-1'

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [datadog]
    metrics:
      receivers: [otlp]
      exporters: [datadog]

  extensions: [pprof]
  telemetry:
    logs:
      level: debug
